package com.telrob.web.mapper;

import com.telrob.web.entity.UserMenu;
import com.telrob.web.entity.UserMenuExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int countByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int deleteByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int insert(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int insertSelective(UserMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    List<UserMenu> selectByExample(UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserMenu record, @Param("example") UserMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_menu
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserMenu record, @Param("example") UserMenuExample example);
}